// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/flnd/v1/flnd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ssigmaapi.Flnd.V1 {

  /// <summary>Holder for reflection information generated from ssigmaapi/flnd/v1/flnd.proto</summary>
  public static partial class FlndReflection {

    #region Descriptor
    /// <summary>File descriptor for ssigmaapi/flnd/v1/flnd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FlndReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxzc2lnbWFhcGkvZmxuZC92MS9mbG5kLnByb3RvEhFzc2lnbWFhcGkuZmxu",
            "ZC52MRobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvIh0KDVZpdGVzc01l",
            "c3NhZ2USDAoEdGV4dBgBIAEoCTLCAgoPVml0ZXNzU2VydmljZVYxEkgKCkdl",
            "dE1lc3NhZ2USFi5nb29nbGUucHJvdG9idWYuRW1wdHkaIC5zc2lnbWFhcGku",
            "ZmxuZC52MS5WaXRlc3NNZXNzYWdlIgASSwoNQ3JlYXRlTWVzc2FnZRIgLnNz",
            "aWdtYWFwaS5mbG5kLnYxLlZpdGVzc01lc3NhZ2UaFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkiABJLCg1VcGRhdGVNZXNzYWdlEiAuc3NpZ21hYXBpLmZsbmQu",
            "djEuVml0ZXNzTWVzc2FnZRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEksK",
            "DURlbGV0ZU1lc3NhZ2USIC5zc2lnbWFhcGkuZmxuZC52MS5WaXRlc3NNZXNz",
            "YWdlGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgBCLlosZ2l0aHViLmNvbS9z",
            "YW5zaWdtYS9zc2lnbWFhcGlnby9mbG5kL3YxO2ZsbmRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ssigmaapi.Flnd.V1.VitessMessage), global::Ssigmaapi.Flnd.V1.VitessMessage.Parser, new[]{ "Text" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VitessMessage : pb::IMessage<VitessMessage> {
    private static readonly pb::MessageParser<VitessMessage> _parser = new pb::MessageParser<VitessMessage>(() => new VitessMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VitessMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ssigmaapi.Flnd.V1.FlndReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VitessMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VitessMessage(VitessMessage other) : this() {
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VitessMessage Clone() {
      return new VitessMessage(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VitessMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VitessMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VitessMessage other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
