// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/flnd/v1/flnd.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ssigmaapi.Flnd.V1 {
  public static partial class VitessServiceV1
  {
    static readonly string __ServiceName = "ssigmaapi.flnd.v1.VitessServiceV1";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ssigmaapi.Flnd.V1.VitessMessage> __Marshaller_ssigmaapi_flnd_v1_VitessMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ssigmaapi.Flnd.V1.VitessMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Ssigmaapi.Flnd.V1.VitessMessage> __Method_GetMessage = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Ssigmaapi.Flnd.V1.VitessMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMessage",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ssigmaapi_flnd_v1_VitessMessage);

    static readonly grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateMessage = new grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateMessage",
        __Marshaller_ssigmaapi_flnd_v1_VitessMessage,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateMessage = new grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateMessage",
        __Marshaller_ssigmaapi_flnd_v1_VitessMessage,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteMessage = new grpc::Method<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteMessage",
        __Marshaller_ssigmaapi_flnd_v1_VitessMessage,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ssigmaapi.Flnd.V1.FlndReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VitessServiceV1</summary>
    public abstract partial class VitessServiceV1Base
    {
      public virtual global::System.Threading.Tasks.Task<global::Ssigmaapi.Flnd.V1.VitessMessage> GetMessage(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CreateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VitessServiceV1</summary>
    public partial class VitessServiceV1Client : grpc::ClientBase<VitessServiceV1Client>
    {
      /// <summary>Creates a new client for VitessServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VitessServiceV1Client(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VitessServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VitessServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VitessServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VitessServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ssigmaapi.Flnd.V1.VitessMessage GetMessage(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ssigmaapi.Flnd.V1.VitessMessage GetMessage(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ssigmaapi.Flnd.V1.VitessMessage> GetMessageAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ssigmaapi.Flnd.V1.VitessMessage> GetMessageAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMessage, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateMessage, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateMessage, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteMessage(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteMessageAsync(global::Ssigmaapi.Flnd.V1.VitessMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override VitessServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new VitessServiceV1Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(VitessServiceV1Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMessage, serviceImpl.GetMessage)
          .AddMethod(__Method_CreateMessage, serviceImpl.CreateMessage)
          .AddMethod(__Method_UpdateMessage, serviceImpl.UpdateMessage)
          .AddMethod(__Method_DeleteMessage, serviceImpl.DeleteMessage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, VitessServiceV1Base serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Ssigmaapi.Flnd.V1.VitessMessage>(serviceImpl.GetMessage));
      serviceBinder.AddMethod(__Method_CreateMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CreateMessage));
      serviceBinder.AddMethod(__Method_UpdateMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateMessage));
      serviceBinder.AddMethod(__Method_DeleteMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ssigmaapi.Flnd.V1.VitessMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteMessage));
    }

  }
}
#endregion
