// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/pashirirest/v1/pashirirest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ssigmaapi.Pashirirest.V1 {

  /// <summary>Holder for reflection information generated from ssigmaapi/pashirirest/v1/pashirirest.proto</summary>
  public static partial class PashirirestReflection {

    #region Descriptor
    /// <summary>File descriptor for ssigmaapi/pashirirest/v1/pashirirest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PashirirestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipzc2lnbWFhcGkvcGFzaGlyaXJlc3QvdjEvcGFzaGlyaXJlc3QucHJvdG8S",
            "GHNzaWdtYWFwaS5wYXNoaXJpcmVzdC52MRobc3NpZ21hYXBpL3R5cGUvbWFy",
            "a2V0LnByb3RvGh5zc2lnbWFhcGkvdHlwZS9vcmRlcmJvb2sucHJvdG8yXQoU",
            "UGFzaGlyaVJlc3RTZXJ2aWNlVjESRQoMR2V0T3JkZXJCb29rEhYuc3NpZ21h",
            "YXBpLnR5cGUuTWFya2V0Ghkuc3NpZ21hYXBpLnR5cGUuT3JkZXJCb29rIgAw",
            "AUI6WjhnaXRodWIuY29tL2thaXRvMi9zc2lnbWFhcGlnby9wYXNoaXJpcmVz",
            "dC92MTtwYXNoaXJpcmVzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ssigmaapi.Type.MarketReflection.Descriptor, global::Ssigmaapi.Type.OrderbookReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
