// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/pashirirest/v1/pashirirest.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ssigmaapi.Pashirirest.V1 {
  public static partial class PashiriRestServiceV1
  {
    static readonly string __ServiceName = "ssigmaapi.pashirirest.v1.PashiriRestServiceV1";

    static readonly grpc::Marshaller<global::Ssigmaapi.Type.Market> __Marshaller_ssigmaapi_type_Market = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ssigmaapi.Type.Market.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ssigmaapi.Type.OrderBook> __Marshaller_ssigmaapi_type_OrderBook = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ssigmaapi.Type.OrderBook.Parser.ParseFrom);

    static readonly grpc::Method<global::Ssigmaapi.Type.Market, global::Ssigmaapi.Type.OrderBook> __Method_GetOrderBook = new grpc::Method<global::Ssigmaapi.Type.Market, global::Ssigmaapi.Type.OrderBook>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetOrderBook",
        __Marshaller_ssigmaapi_type_Market,
        __Marshaller_ssigmaapi_type_OrderBook);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ssigmaapi.Pashirirest.V1.PashirirestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PashiriRestServiceV1</summary>
    public abstract partial class PashiriRestServiceV1Base
    {
      public virtual global::System.Threading.Tasks.Task GetOrderBook(global::Ssigmaapi.Type.Market request, grpc::IServerStreamWriter<global::Ssigmaapi.Type.OrderBook> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PashiriRestServiceV1</summary>
    public partial class PashiriRestServiceV1Client : grpc::ClientBase<PashiriRestServiceV1Client>
    {
      /// <summary>Creates a new client for PashiriRestServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PashiriRestServiceV1Client(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PashiriRestServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PashiriRestServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PashiriRestServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PashiriRestServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Ssigmaapi.Type.OrderBook> GetOrderBook(global::Ssigmaapi.Type.Market request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrderBook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ssigmaapi.Type.OrderBook> GetOrderBook(global::Ssigmaapi.Type.Market request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetOrderBook, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PashiriRestServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new PashiriRestServiceV1Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PashiriRestServiceV1Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetOrderBook, serviceImpl.GetOrderBook).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PashiriRestServiceV1Base serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetOrderBook, serviceImpl.GetOrderBook);
    }

  }
}
#endregion
