// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/pashiriwebsocket/v1/pashiriwebsocket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ssigmaapi.Pashiriwebsocket.V1 {

  /// <summary>Holder for reflection information generated from ssigmaapi/pashiriwebsocket/v1/pashiriwebsocket.proto</summary>
  public static partial class PashiriwebsocketReflection {

    #region Descriptor
    /// <summary>File descriptor for ssigmaapi/pashiriwebsocket/v1/pashiriwebsocket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PashiriwebsocketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRzc2lnbWFhcGkvcGFzaGlyaXdlYnNvY2tldC92MS9wYXNoaXJpd2Vic29j",
            "a2V0LnByb3RvEh1zc2lnbWFhcGkucGFzaGlyaXdlYnNvY2tldC52MRobc3Np",
            "Z21hYXBpL3R5cGUvbWFya2V0LnByb3RvGhpzc2lnbWFhcGkvdHlwZS90cmFk",
            "ZS5wcm90bzJcChlQYXNoaXJpV2Vic29ja2V0U2VydmljZVYxEj8KCUdldFRy",
            "YWRlcxIWLnNzaWdtYWFwaS50eXBlLk1hcmtldBoWLnNzaWdtYWFwaS50eXBl",
            "LlRyYWRlcyIAMAFCRFpCZ2l0aHViLmNvbS9rYWl0bzIvc3NpZ21hYXBpZ28v",
            "cGFzaGlyaXdlYnNvY2tldC92MTtwYXNoaXJpd2Vic29ja2V0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ssigmaapi.Type.MarketReflection.Descriptor, global::Ssigmaapi.Type.TradeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
